# appspec.yml
version: 0.0
os: linux
resources:
  - myLambdaFunction:
      type: AWS::Lambda::Function
      properties:
        Name: "funcA-poc" # Your Lambda function name
        Alias: "PROD"    # The alias CodeDeploy will manage
        CurrentVersion: "$LATEST"
        TargetVersion: "NewFunctionVersion"